#!/usr/bin/env bash 

running="running"

if [ "$ACTION" == "enable" ]; then
  if [ "$ROOT" == "true" ]; then
    systemctl enable "${SERVICE}" --now
    output=$(systemctl show -p SubState --value "$SERVICE")
    if [[ $output != "$running" ]]; then
      exit 1
    fi
  else
    systemctl --user enable "${SERVICE}" --now
    output=$(systemctl --user show -p SubState --value "$SERVICE")
    if [[ $output != "$running" ]]; then
      exit 1
    fi
  fi
fi

if [ "$ACTION" == "restart" ]; then
  if [ "$ROOT" == "true" ]; then
    systemctl stop "${SERVICE}"
    sleep 3
    systemctl enable "${SERVICE}" --now
    output=$(systemctl show -p SubState --value "$SERVICE")
    if [[ $output != "$running" ]]; then
      exit 1
    fi
  else
    systemctl --user stop "${SERVICE}"
    sleep 3
    systemctl --user enable "${SERVICE}" --now
    output=$(systemctl --user show -p SubState --value "$SERVICE")
    if [[ $output != "$running" ]]; then
      exit 1
    fi
  fi
fi
