# BUILD STAGE
FROM registry.access.redhat.com/ubi8/go-toolset as builder
USER root

RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin 

# RUN STAGE
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
USER root

COPY --from=builder /usr/local/bin/syft /usr/local/bin/
