targetConfigs:
- name: fetchit
  url: http://github.com/containers/fetchit
  methods:
  - kind: filetransfer
    name: ft-example
    targetPath: examples/filetransfer/
    destinationDirectory: /tmp/ft
    schedule: "*/1 * * * *"
  branch: ci
