targetConfigs:
- url: http://localhost:10080/sallyom/fetchit-local
  filetransfer:
  - name: ft-example
    targetPath: examples/filetransfer
    destinationDirectory: /tmp/ft
    schedule: "*/1 * * * *"
  branch: ci
