# for this test, start with this config, then wait to be sure the
# targets from .harpoon/config.yaml are populated
# and for follow-up test, push a change to the config and confirm
# new targets are fetched & run
targets:
- name: config
  methods:
    configTarget:
      configUrl: https://raw.githubusercontent.com/sallyom/harpoon/demo-sysd-config/examples/config-reload.yaml
      schedule: "*/2 * * * *"
- name: harpoon
  url: https://github.com/sallyom/harpoon
  methods:
    filetransfer:
      targetPath: examples/filetransfer
      destinationDirectory: /tmp/ft
      schedule: "*/1 * * * *"
  branch: demo-sysd-config
