targets:
- name: config
  methods:
    configTarget:
      configUrl: https://raw.githubusercontent.com/sallyom/harpoon/demo-sysd-config/examples/config-reload.yaml
      schedule: "*/2 * * * *"
- name: sigstore
  url: https://github.com/sallyom/sigstore-the-local-way
  branch: main
  methods:
    filetransfer:
      targetPath: launch-sigstore.sh
      destinationDirectory: /tmp/sigstore
      schedule: "*/1 * * * *"
- name: harpoon
  url: http://github.com/sallyom/harpoon
  methods:
    systemd:
      targetPath: examples/systemd/httpd.service
      schedule: "*/3 * * * *"
      enable: true
      root: true
    filetransfer:
      targetPath: examples/filetransfer
      destinationDirectory: /tmp/ft
      schedule: "*/1 * * * *"
  branch: demo-sysd-config
