# for this test, start with this config, then wait to be sure the
# targets from .harpoon/config.yaml are populated
# and for follow-up test, push a change to the config and confirm
# new targets are fetched & run
targets:
- name: microshift
  url: https://github.com/redhat-et/microshift
  branch: main
  methods:
    systemd:
      targetPath: packaging/systemd/microshift-aio.service
      root: true
      enable: true
      schedule: "*/1 * * * *"
- name: harpoon
  url: http://github.com/sallyom/harpoon
  methods:
    configTarget:
      configUrl: https://raw.githubusercontent.com/sallyom/harpoon/config-upload/examples/config-reload.yaml
      schedule: "*/1 * * * *"
    filetransfer:
      targetPath: examples/filetransfer
      destinationDirectory: /tmp/new
      schedule: "*/1 * * * *"
  branch: config-upload
