# for this test, start with this config, then wait to be sure the
# targetConfigs from .fetchit/config.yaml are populated
# and for follow-up test, push a change to the config and confirm
# new targetConfigs are fetched & run
configReload:
  configURL: http://localhost:10080/sallyom/fetchit-local/raw/main/examples/config-reload.yaml
  schedule: "*/2 * * * *"
targetConfigs:
- url: http://localhost:10080/sallyom/fetchit-local
  raw:
  - name: raw-ex
    targetPath: examples/raw
    schedule: "*/1 * * * *"
    pullImage: false
  branch: main
