targetConfigs:
- url: http://localhost:10080/sallyom/fetchit-local
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    glob: "hello.txt"
    destinationDirectory: /tmp/ft/single
    schedule: "*/1 * * * *"
  branch: main
