targetConfigs:
- url: https://localhost:10080/sallyom/fetchit-local
  verifyCommitsInfo:
    GitsignVerify: true
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    destinationDirectory: /tmp/ft
    schedule: "*/1 * * * *"
  branch: gitsign
