images:
  - name: httpd-ex
    url: http://localhost:8080/httpd.tar
    schedule: "*/1 * * * *"
targetConfigs:
- url: http://localhost:10080/sallyom/fetchit-local
  raw:
  - name: raw-ex
    targetPath: examples/imageLoad
    schedule: "*/1 * * * *"
    pullImage: false
  branch: main
