targetConfigs:
- name: fetchit
  url: https://github.com/containers/fetchit
  methods:
  - kind: raw
    name: raw-ex
    targetPath: examples/raw/
    schedule: "*/1 * * * *"
    pullImage: false
  branch: main
