targetConfigs:
- url: http://localhost:10080/sallyom/fetchit-local
  branch: main
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    glob: "hello.txt"
    destinationDirectory: /tmp
    schedule: "*/1 * * * *"
  raw:
  - name: raw-ex
    targetPath: examples/raw
    schedule: "*/1 * * * *"
