gitAuth:
  ssh: true
  sshKeyFile: test_id_rsa
targetConfigs:
- url: git@github.com:containers/fetchit
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    destinationDirectory: /tmp/ft
    schedule: "*/1 * * * *"
  branch: main
