targetConfigs:
- url: http://localhost:10080/sallyom/fetchit-local
  systemd:
  - name: sysd-ex
    targetPath: examples/systemd
    root: true
    enable: false
    schedule: "*/1 * * * *"
  branch: main
